# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-28 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
